image: 'ruby:2.6.3'

before_script:
  - ruby --version
  - gem update --system
  - gem --version
  - gem install bundler -v '~> 2'
  - bundle --version
  - bundle install --jobs=3 --retry=3

rspec:
  script:
    - bundle exec rspec
